### PR TITLE
Dive support added

### PR DESCRIPTION
**Pull request by jrmcdaniel**
If the previous crash was due to something I'm doing and not due to OS webhooks, let me know and I'll put a pause on adding the new projects.

### CODE REVIEW

**Comment by jakerockland** [comment]
Closes #154 

@ryley-o would you PTAL on reviewing this one?

**Comment by jrmcdaniel** [comment]
Updated with Bent as well.

**Comment by ryley-o** [comment]
Awesome, thanks! also, @jrmcdaniel nothing you did last time would have caused artbot to break that I know of.

I can take a look at this on 11/30 (in addition to a bunch of other artbot items) 😄

**Review by ryley-o — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
