### PR TITLE
Aurora IV bot for ge1doot channel

### PR DESCRIPTION
**Pull request by sukoneck**
Long time listener first time caller 🌈

### CODE REVIEW

**Comment by jakerockland** [comment]
Fantastic, thank you!!

**Comment by sukoneck** [comment]
Thanks @jakerockland! FYI I tested this here and is still defaulting to Ignition project: https://discord.com/channels/411959613370400778/807346227594919986/882360389533315092

Did I miss something or does bot need redeploying?

**Comment by jakerockland** [comment]
Just hadn't been redeployed yet post-merge (that isn't automatic, yet), but it is now :)

**Comment by sukoneck** [comment]
sweet! happy to help with pipeline, just lmk 🤝

**Pull request merged**
